# Generated by Django 3.2.7 on 2021-10-06 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='room', to='Chat.room'),
            preserve_default=False,
        ),
    ]
